### PR TITLE
Update com.github.torikulhabib.niki.pot

### PR DESCRIPTION
**Pull request by safak45x**
pls add Turkish translate

if you see error please message

### CODE REVIEW

**Comment by torikulhabib** [comment]
Ok thanks.

**Review by NathanBnm — CHANGES_REQUESTED** [review]
This should not be merged directly. You cannot edit the `.pot` file to add a language. This is a template file.
You have to create a `tr.po` file both in the `po` and the `po/extra` folder instead in order to add Turkish.

**Comment by safak45x** [comment]
> This should not be merged directly. You cannot edit the `.pot` file to add a language. This is a template file.
> You have to create a `tr.po` file both in the `po` and the `po/extra` folder instead in order to add Turkish.

but no tr.po file, what do I do?

I'm currently working on the .extra file

**Comment by NathanBnm** [comment]
You have to create it if it doesn't exist. You just have to move the changes you made to the `.pot` file into the `tr.po` file you will have created.

Same for the extra part.

**Comment by safak45x** [comment]
> You have to create it if it doesn't exist. You just have to move the changes you made to the `.pot` file into the `tr.po` file you will have created.
> 
> Same for the extra part.

Thank you
Question marks in my head are now resolved.
Should I remove this file or would you add it?

**Comment by NathanBnm** [comment]
You can edit the file into the "patch-2" branch of your copy of the repository to revert your changes and move them into the new file. This way you will update this pull request automatically.

But if it's easier to you, you can create a new pull request by creating the appropriate `tr.po` file and then close this one.

**Pull request closed without merging**
